name: Publish Jellyfin Plugin
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-jellyfin-plugin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: repository
        path: Repository
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add Source Credential
      run: |
        dotnet nuget remove source "github.com/$GITHUB_REPOSITORY_OWNER"
        dotnet nuget add source --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text \
          --name "github.com/$GITHUB_REPOSITORY_OWNER" "https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json"
    - name: Install jprm
      run: pip install jprm~=1.1
    - name: Build & Package
      run: python3 jprmbuild.py "$GITHUB_REPOSITORY"
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "$GITHUB_REF_NAME" ./artifacts/*.zip --generate-notes --verify-tag
    - name: Push Repository Index
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd Repository
        cp -f ../artifacts/manifest.json ./
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        branch_name="update-repo-$GITHUB_REF_NAME"
        git checkout -b "$branch_name"
        git add manifest.json
        commit_msg="Add $GITHUB_REF_NAME to Repository"
        git commit -m "$commit_msg"
        git push -u origin "$branch_name"
        gh pr create --assignee "$GITHUB_REPOSITORY_OWNER" --title "$commit_msg" --body "" --base repository
